### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by brsbl** [brsbl/brsbl.github.io#3]
**TODOs**

- [x] settle on formatting, style, and [color palette](https://colorhunt.co/)
- [x] update CSS
- [x] fix scrolling
- [x] make mobile-friendly/responsive
- [x] update and post first blog post on [tiny letter](https://app.tinyletter.com/#!/messages/drafts)
- [x] replace lorem ipsum with first blog post
- [x] remove additional photos and art
